name: deploy-proxy.yml

on:
  workflow_dispatch:
    inputs:
      deploy_prod:
        description: 'Deploy to production'
        type: boolean
        required: false
        default: false

jobs:
  build-test-push-image:
    name: Build, test and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 'wrapper'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Run Gradle build
        shell: bash
        run: ./gradlew build

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: supstonad
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: 'Dockerfile'
          image_suffix: 'app'
          docker_context: './server'

  deploy-dev:
    needs: build-test-push-image
    runs-on: ubuntu-latest
    name: Deploy to preprod
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/dev.yaml
          VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/supstonad-proxy-fss-app:${{ github.sha }}

  deploy-prod:
    needs: build-test-push-image
    if: ${{ inputs.deploy_prod == true && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Deploy to prod
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/prod.yaml
          VAR: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/supstonad-proxy-fss-app:${{ github.sha }}
