name: deploy-proxy.yml

on:
  workflow_dispatch:

jobs:
  build-test-push-image:
    name: Build, test and push image
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.docker_image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: 'wrapper'

      - name: Run Gradle build
        shell: bash
        run: ./gradlew build

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: supstonad
          tag: ${{ github.sha }}
          identity_provider: ${{ inputs.identity_provider }}
          project_id: ${{ inputs.project_id }}
          dockerfile: 'Dockerfile'
          image_suffix: 'app'

  deploy:
    needs: build-test-push-image
    runs-on: ubuntu-latest
    name: Deploy to preprod
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy to cluster
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: server/.nais/dev.yaml
          VAR: image=${{ steps.docker-build-push.outputs.docker_image }}
